version: "3.3"
services:
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    image: php:8.1-apache
    volumes:
      - ./app/:/var/www
      - ./app/configPHP/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "80:80"
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "recipebuddy"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
volumes:
  mysqldata: {}