version: "3.3"
services:
  web:
    environment:
      - APACHE_RUN_USER=#1000
    build:
      context: ./docker/web
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/html
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "recipebuddy"
    volumes:
      - ./docker/database:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
volumes:
  mysqldata: {}
