name: Deploy to Main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update and install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client rsync
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - run: ls
      - run: pwd
      - run: ls
      - run: cd ../
      - run: pwd
      - run: ls
      - name: Deploy to website.cs350.melvinauvray.com
        run: |
          rsync -atv -e 'ssh -p 5022 -o StrictHostKeyChecking=no' --progress --delete /home/runner/work/CS350/website/ pjywaxcr@nodels42-eu.n0c.com:website.cs350.melvinauvray.com
